version: '2.1'
services:
    product-ui:
        image: product-ui:0.0.1
        ports: 
          - "82:80"
        container_name: product-ui        
        networks : 
          - demo_network
    product-service:
        image: product-service:0.0.1
        ports:
          - "9090:8080"
        container_name: product-service
        volumes:
          - myVol:/my-logs
        networks : 
          - demo_network
    book-service:
         image: book-service:0.0.1
         ports:
         - "9001:8081"
         container_name: book-service
         volumes:
          - myVol:/my-logs
         networks : 
         - demo_network    
        
networks:
    demo_network:
       name: demo_network1    
       driver : bridge
volumes:
    myVol: